Add BelongsTo handling in DataMapper
LASTRADA-Software/Lightweight pull request #139
Opened 2024-12-13 16:15 UTC by Yaraslaut

2024-12-14 00:19 UTC, christianparpart commented
```
  42000 (3726) - [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Could
  not drop object 'User' because it is referenced by a FOREIGN KEY constraint.
```

I think here are two ways to fix this when dropping all tables in the CI fixture:

1. We either use Fixed-Point Iteration style algorithm until all tables are dropped, e.g. re-iterate over all not-yet-dropped tables until they are dropped. this way you'll impliictely have deleded all referencing tables first. 
2. Or we actually inspect the tables to be dropped, and recursively drop the referencing tables first, like a `DropTableRecursively<Record>()`. AFAICT, we should be even able to solve the order of deletion at compile time, because we have all the info at compile time already. Similar to how we find the primary keys / foreign keys in a table struct right now already, too.

Having that one written out, I think the second solution is certainly way more sexy, but involves more thinking.

2024-12-14 10:45 UTC, Yaraslaut commented
I will go with second option, will update PR soon

2024-12-14 21:11 UTC, christianparpart requested changes

2024-12-14 21:11 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                                                   .columnName = "id" });
I think `"id"` may potentially be wrong. Because the foreign key's referenced column name is not mandated to be named `"id"`. :thinking:

2024-12-14 21:11 UTC, christianparpart commented on src/tests/DataMapperTests.cpp
> +        REQUIRE(dm.CreateTableString<Email>(dm.Connection().ServerType())[0]
instead of calling `[0]` here, I think we should instead put both `NormalizeText(..)` helper methods into tests/Utils.hpp and use those instead.

2024-12-15 18:32 UTC, Yaraslaut commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                                                   .columnName = "id" });
Fixed, now we check for primary key name

2024-12-15 18:43 UTC, Yaraslaut commented on src/tests/DataMapperTests.cpp
> +        REQUIRE(dm.CreateTableString<Email>(dm.Connection().ServerType())[0]
Switched to `NormalizeText` function

2024-12-15 19:59 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                                        index = J;
```suggestion
                                        return J;
```

2024-12-15 19:59 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                        size_t index = -1;
```suggestion
```

2024-12-15 19:59 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                        return index;
and then, return here something symbolic to signal that nothing was found.
Giving it a second thought. I think this should never be possible (or is it?) In that case, we could `static_assert(false, "reason");` here, assuming that this works on all 3 compilers, latest version.

2024-12-15 19:59 UTC, christianparpart commented on src/tests/DataMapperTests.cpp
> +    if (dm.Connection().ServerType() == SqlServerType::SQLITE)
Why only if Sqlite? Or is it just to see if it generally works?

2024-12-15 19:59 UTC, christianparpart commented on src/tests/DataMapperTests.cpp
> +    if (dm.Connection().ServerType() == SqlServerType::SQLITE)
squared :)

2024-12-15 20:07 UTC, Yaraslaut commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                                        index = J;
I think this is not possible since you can not return out of scope of `Reflection::EnumerateMembers` the only way to return something from there is through lambda capture

2024-12-15 20:08 UTC, Yaraslaut commented on src/tests/DataMapperTests.cpp
> +    if (dm.Connection().ServerType() == SqlServerType::SQLITE)
just to see that everything is working, did not want to bother writing comparison for every database type

2024-12-15 20:23 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                                        index = J;
brain damage on my end. apologees. need to rethink :)

2024-12-15 20:52 UTC, Yaraslaut commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                        return index;
the default value of -1 ensures that if we never find primary key compilation will fail since struct member will not exist

2024-12-17 22:34 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +    ();
is this really the syntax of clang-format? :thinking:

2024-12-17 22:34 UTC, christianparpart commented on src/tests/DataMapperTests.cpp
> +                == "CREATE TABLE \"Email\" (\n"
I think it's better to use raw string literals here rather than many string literals that need escaping. Should be easier to read, isn't it?

NormalizeText() takes care of not having to deal with indentation width etc.

2024-12-18 09:56 UTC, Yaraslaut commented on src/tests/DataMapperTests.cpp
> +                == "CREATE TABLE \"Email\" (\n"
Fixed

2024-12-18 20:06 UTC, christianparpart commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                    size_t ind = -1;
One last comment, just for the record, and similar to how we should dothings in Contour (of course :D). Let's try to avoid abbreviations unless they're very well known. :)

2024-12-18 20:08 UTC, christianparpart approved these changes
Many thanks :christmas_tree:

2024-12-19 09:21 UTC, Yaraslaut commented on src/Lightweight/DataMapper/DataMapper.hpp
> +                    size_t ind = -1;
renamed it into `index`

2024-12-19 09:26 UTC, merged