Add documentation for sql query builder
LASTRADA-Software/Lightweight pull request #165
Opened 2024-12-28 11:39 UTC by Yaraslaut

Add documentation for sql query builder to cover some common use cases and have one place with a short list of available functions

2025-01-01 20:56 UTC, christianparpart requested changes
What do we do with the TODO(pr)'s?

2025-01-01 20:56 UTC, christianparpart commented on src/Lightweight/SqlQuery/Migrate.hpp
> +    //TODO(PR) CHANGE NAME ?
What should we do about these TODO(PR) comments? Change name to what?

2025-01-01 21:07 UTC, Yaraslaut commented on src/Lightweight/SqlQuery/Migrate.hpp
> +    //TODO(PR) CHANGE NAME ?
We have different behavior for the CreateTable and AlterTable nested functions, for example while AddColumn in CreateTable makes it optional, AddColumn in AlterTable makes it required, so we need to have same behavior for this cases, that is why i left this TODO, to figure out where to rename to what

2025-01-01 21:15 UTC, christianparpart commented on src/Lightweight/SqlQuery/Migrate.hpp
> +    //TODO(PR) CHANGE NAME ?
oh damn. remind me tomorrow, so we can talk about it in person. :thinking:

2025-01-02 21:00 UTC, christianparpart approved these changes
nice. thank you. :)

2025-01-02 21:01 UTC, merged